- name: configure rabbitmq 
  hosts: rabbitmq 
  become: yes 
  tasks: 
  - name: copy repos of rabbitmq 
    ansible.builtin.copy: 
      src: rabbitmq.repo 
      dest: /etc/yum.repos.d/rabbitmq.repo 
  
  - name: install rabbbitmq 
    ansible.builtin.dnf: 
      name: rabbitmq-server
      state: present 

  - name: enable and start service 
    ansible.builtin.service: 
      name: rabbitmq-server 
      state: started 
      enabled: yes 
  
  
  - name: create rabbitmq user 
    community.rabbitmq.rabbitmq_user: 
      user: roboshop 
      password: roboshop123 
      permissions: 
        - vhost: / 
          configure_priv: .*
          read_priv: .* 
          write_priv: .* 
      state: present 



